//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestBack.Models.ModelSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class autor
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public string ciudad { get; set; }
        public string email { get; set; }
    }
}
