//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestBack.Models.ModelSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class libro
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public Nullable<int> anno { get; set; }
        public string genero { get; set; }
        public Nullable<int> paginas { get; set; }
        public string autor { get; set; }
    }
}
